name: 'tests Linux'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  linux:

    runs-on: ubuntu-20.04
    env:
        VULKAN_SDK_VERSION: 1.2.170
    strategy:
      matrix:
        include:
          - backend: "all"
            run_tests_command: "DEBUG=yes DEBUG_GL=yes make tests"
          - backend: "opengles 2"
            run_tests_command: "MESA_GLES_VERSION_OVERRIDE=2.0 DEBUG=yes DEBUG_GL=yes make tests TESTS_SUITE=opengles"

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        sudo apt -y update
        #
        # python3-venv is required to prevent the following issue:
        #     The virtual environment was not created successfully because ensurepip is not
        #     available.  On Debian/Ubuntu systems, you need to install the python3-venv
        #     package using the following command.
        #
        #         apt-get install python3-venv
        #
        sudo apt -y install libsdl2-dev python3-venv
        sudo apt -y install ffmpeg libavcodec-dev libavutil-dev libavformat-dev libavdevice-dev \
            libavfilter-dev libswscale-dev libswresample-dev libpostproc-dev ninja-build libglm-dev \
            libglfw3-dev libglew-dev renderdoc
        # Install Vulkan SDK
        wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-${{env.VULKAN_SDK_VERSION}}-focal.list https://packages.lunarg.com/vulkan/${{env.VULKAN_SDK_VERSION}}/lunarg-vulkan-${{env.VULKAN_SDK_VERSION}}-focal.list
        sudo apt -y update
        sudo apt install vulkan-sdk
    - name: Build
      run: |
        make DEBUG_GPU_CAPTURE=yes
    - name: Run tests ${{matrix.backend}}
      run: |
        ${{matrix.run_tests_command}}

