name: 'tests MSVC'

on:
  push:
    branches:
      - 'master'
  pull_request:
  schedule:
      - cron: "0 0 * * 6"  # Run every Saturday at midnight

jobs:
  msvc:

    runs-on: windows-latest
    env:
        VCPKG_TRIPLET: x64-windows
        VCPKG_INSTALL_PACKAGES: opengl-registry ffmpeg[ffmpeg,ffprobe] sdl2 spirv-cross

    defaults:
      run:
        shell: wsl-bash {0}

    steps:
      - uses: Vampire/setup-wsl@v1
        with:
          distribution: Ubuntu-20.04

      - uses: actions/checkout@v2

      - name: Get vcpkg cache key
        id: get-vcpkg-cache-key
        run: |
          VCPKG_COMMIT_ID=$(cd /mnt/c/vcpkg && git rev-parse HEAD)
          echo "::set-output name=key::$(echo $VCPKG_COMMIT_ID ${{env.VCPKG_TRIPLET}} ${{env.VCPKG_INSTALL_PACKAGES}} | md5sum | cut -f1 -d" ")"

      - name: Restore vcpkg binary cache archives
        id: restore_vcpkg_binary_cache
        uses: actions/cache@v2
        with:
          path: C:\Users\runneradmin\AppData\Local\vcpkg\archives
          key: ${{ steps.get-vcpkg-cache-key.outputs.key }}

      - name: Install dependencies
        run: |
          sudo apt -y update
          sudo apt -y install build-essential unzip
          pip.exe install meson
          wget https://sdk.lunarg.com/sdk/download/1.2.162.1/windows/VulkanSDK-1.2.162.1-Installer.exe
          chmod a+x VulkanSDK-1.2.162.1-Installer.exe
          ./VulkanSDK-1.2.162.1-Installer.exe /S
          cd /mnt/c/vcpkg
          ./vcpkg.exe install --triplet ${{env.VCPKG_TRIPLET}} ${{env.VCPKG_INSTALL_PACKAGES}}

      - name: Build
        run: |
          cd /mnt/c
          # Workaround for meson issue #8329
          # Currently meson requires the project to be on the same drive as dependencies
          cp -Rf /mnt/d/a/gopro-lib-node.gl/gopro-lib-node.gl .
          cd gopro-lib-node.gl
          # Save the following commands to a variable
          read -r -d '' COMMANDS << EOM || true
          source build_scripts/windows/set_env.sh
          make -j$(($(nproc)+1))
          EOM
          tmpfile=$(mktemp)
          echo "$COMMANDS" > $tmpfile
          # Execute the commands in an msvc dev environment
          bash build_scripts/windows/start_msvc_env.sh $tmpfile
